const locations = [

    "Delhi",
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Chandigarh",
    "Amritsar",
    "Ludhiana",
    "Shimla",
    "Dehradun",
    "Haridwar",
    "Rishikesh",
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Panaji",
    "Vasco Da Gama",
 
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Hyderabad",
    "Warangal",
    "Kochi",
    "Kolkata",
    "Siliguri",
    "Durgapur",
    "Asansol",
    "Bhubaneswar",
    "Cuttack",
    "Puri",
    "Ranchi",
    "Jamshedpur",
    "Patna",
    "Gaya"
  
];

export default locations;